language: android
sudo: false
jdk: oraclejdk8
env:
   matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
  global:
    - ANDROID_API=26
    - ANDROID_BUILD_TOOLS=26.0.2
    - ADB_INSTALL_TIMEOUT=10

# to avoid uploading the cache after every build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

android:
  components:
  # running tools twice, get the latest build tools
  # https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI   
  - tools
  - tools 
  - platform-tools
  - android-${ANDROID_API}
  - build-tools-${ANDROID_BUILD_TOOLS}

  # additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis_google-26

  # emulator for tests
  - sys-img-armeabi-v7a-android-22